[mypy]
python_version = 3.12
warn_return_any = true
warn_unused_configs = true
check_untyped_defs = true
disallow_incomplete_defs = true
ignore_missing_imports = true

[mypy-*.migrations.*]
ignore_errors = true
