# Generated by Django 5.2.6 on 2026-01-14 18:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_item_created_at_item_image_item_starting_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='api.bid')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_bids', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'bid')},
            },
        ),
    ]
