# Generated by Django 5.2.6 on 2026-01-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_seed_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
